# Generated by Django 5.1.3 on 2024-12-12 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0004_employee_priority_alter_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reg_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data Registration Date"
            ),
        ),
    ]
